apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: gitpods-try
  labels:
    app: storage
spec:
  type: ClusterIP
  selector:
    app: storage
  ports:
    - name: http
      protocol: TCP
      port: 3030
      targetPort: 3030
    - name: grpc
      protocol: TCP
      port: 3033
      targetPort: 3033
