workspace:
  base: /go
  path: src/github.com/gitpods/gitpods

pipeline:
  test:
    image: golang:1.10
    commands:
      - go test -v ./...

  dart:
    image: google/dart
    commands:
      - cd ui
      - pub get --no-precompile
      - pub build
      - rm -rf build/web/packages

  api:
    group: build
    image: golang:1.10
    commands:
      - CGO_ENABLED=0 go build -v -ldflags '-w -extldflags '-static'' -o ./cmd/api/api ./cmd/api

  gitpods:
    group: build
    image: golang:1.10
    commands:
      - CGO_ENABLED=0 go build -v -ldflags '-w -extldflags '-static'' -o ./cmd/gitpods/gitpods ./cmd/gitpods

  storage:
    group: build
    image: golang:1.10
    commands:
      - CGO_ENABLED=0 go build -v -ldflags '-w -extldflags '-static'' -o ./cmd/storage/storage ./cmd/storage

  ui:
    group: build
    image: golang:1.10
    commands:
      - curl -s -L https://github.com/gobuffalo/packr/releases/download/v1.10.4/packr_1.10.4_linux_amd64.tar.gz | tar -xz
      - ./packr
      - CGO_ENABLED=0 go build -v -ldflags '-w -extldflags '-static'' -o ./cmd/ui/ui ./cmd/ui

  docker-api:
    group: docker
    image: plugins/docker
    repo: gitpods/api
    dockerfile: ./cmd/api/Dockerfile
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

  docker-storage:
    group: docker
    image: plugins/docker
    repo: gitpods/storage
    dockerfile: cmd/storage/Dockerfile
    context: ./cmd/storage
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

  docker-ui:
    group: docker
    image: plugins/docker
    repo: gitpods/ui
    dockerfile: cmd/ui/Dockerfile
    context: ./cmd/ui
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: master
      event: push

  kubernetes-api:
    group: deployment
    image: vallard/drone-kube
    namespace: gitpods-try
    template: deployment/kubernetes/api/deployment.yml
    secrets: [ KUBE_SERVER, KUBE_CA, KUBE_TOKEN ]
    when:
      branch: master
      event: push

  kubernetes-ui:
    group: deployment
    image: vallard/drone-kube
    namespace: gitpods-try
    template: deployment/kubernetes/ui/deployment.yml
    secrets: [ KUBE_SERVER, KUBE_CA, KUBE_TOKEN ]
    when:
      branch: master
      event: push

  gitter:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
