apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  namespace: gitpods-try
spec:
  replicas: 3
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: gitpods/ui:latest
        env:
        - name: GITPODS_API_URL
          value: 'https://try.gitpods.io/api'
        - name: GITPODS_HTTP_ADDR
          value: '0.0.0.0:3010'
        - name: GITPODS_LOG_LEVEL
          value: 'info'
        - name: GITPODS_LOG_JSON
          value: 'true'
        # This hash is not needed and only used to track which version is deployed when using :latest
        - name: HASH
          value: {{ .DroneCommit }}
        ports:
        - containerPort: 3010
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
