apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitpods
  namespace: gitpods-try
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - try.gitpods.io
    secretName: try-gitpods-tls
  rules:
  - host: try.gitpods.io
    http:
     paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: http
      - path: /api
        backend:
          serviceName: api
          servicePort: 80
