apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: gitpods-try
spec:
  replicas: 3
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "3021"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: api
        image: gitpods/api:latest
        env:
        - name: GITPODS_DATABASE_DRIVER
          value: 'postgres'
        - name: GITPODS_DATABASE_DSN
          value: 'postgres://postgres:postgres@db:5432?sslmode=disable'
        - name: GITPODS_HTTP_ADDR
          value: '0.0.0.0:3020'
        - name: GITPODS_HTTP_ADDR
          value: '0.0.0.0:3020'
        - name: GITPODS_HTTP_PRIVATE_ADDR
          value: '0.0.0.0:3021'
        - name: GITPODS_LOG_JSON
          value: 'true'
        - name: GITPODS_LOG_LEVEL
          value: 'info'
        - name: GITPODS_MIGRATIONS_PATH
          value: '/migrations'
        - name: GITPODS_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: secret
        - name: GITPODS_STORAGE_GRPC_URL
          value: 'storage:3033'
        - name: GITPODS_STORAGE_HTTP_URL
          value: 'storage:3030'
        # This hash is not needed and only used to track which version is deployed when using :latest
        - name: HASH
          value: {{ .DroneCommit }}
        ports:
        - containerPort: 3020
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3021
          initialDelaySeconds: 3
          periodSeconds: 3
